/**
 * Engine Verification Page
 *
 * This page tests that the real Stockfish and Maia engines
 * actually load and work correctly in the browser, and compares
 * results against expected values from Node.js testing.
 *
 * Run with: npm run dev
 * Visit: http://localhost:3000/verify-engines
 *
 * To update expected values, run: npm run test:engines:verbose
 * and copy the results here.
 */

import { useState } from 'react'

// =============================================================================
// TEST CONFIGURATION
// =============================================================================

// Multiple test positions for comprehensive verification
const TEST_POSITIONS = [
  {
    name: 'Starting Position',
    fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    description: 'Initial chess position - White to move',
  },
  {
    name: 'After 1.e4',
    fen: 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
    description: 'Position after 1.e4 - Black to move',
  },
  {
    name: 'Italian Game',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    description: 'Italian Game position - White to move',
  },
  {
    name: 'Sicilian Defense',
    fen: 'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2',
    description: 'Sicilian Defense - White to move',
  },
]

// Default to first position
const DEFAULT_POSITION_INDEX = 0

// =============================================================================
// EXPECTED VALUES FROM NODE.JS TESTING
// These values come from running: npm run test:engines:verbose
// They serve as the "ground truth" to compare browser results against.
// =============================================================================

// Node.js baselines for each test position (indexed by position index)
const EXPECTED_STOCKFISH_BY_POSITION = [
  // Position 0: Starting Position
  {
    bestMoves: ['g1f3', 'd2d4', 'e2e4'],
    evaluationRange: { min: 20, max: 80 },
    nodeJsResult: { bestMove: 'g1f3', evaluation: 58, winrate: 0.583, depth: 10 },
  },
  // Position 1: After 1.e4 (Black to move, eval from Black's POV)
  {
    bestMoves: ['e7e5', 'c7c5', 'e7e6', 'g8f6'],
    evaluationRange: { min: 20, max: 50 },
    nodeJsResult: { bestMove: 'e7e5', evaluation: 34, winrate: 0.451, depth: 10 },
  },
  // Position 2: Italian Game
  {
    bestMoves: ['f3g5', 'd2d3', 'd2d4', 'b1c3'],
    evaluationRange: { min: 20, max: 70 },
    nodeJsResult: { bestMove: 'f3g5', evaluation: 56, winrate: 0.580, depth: 10 },
  },
  // Position 3: Sicilian Defense
  {
    bestMoves: ['f1b5', 'g1f3', 'c2c3', 'b1c3'],
    evaluationRange: { min: 30, max: 90 },
    nodeJsResult: { bestMove: 'f1b5', evaluation: 78, winrate: 0.610, depth: 10 },
  },
]

const EXPECTED_MAIA_BY_POSITION = [
  // Position 0: Starting Position
  {
    nodeJsResult: {
      value: 0.409,
      policy: [
        { move: 'g1f3', probability: 0.334 },
        { move: 'b1c3', probability: 0.241 },
        { move: 'b1a3', probability: 0.076 },
      ],
    },
  },
  // Position 1: After 1.e4 (Black to move)
  {
    nodeJsResult: {
      value: 0.287,
      policy: [
        { move: 'g8f6', probability: 0.312 },
        { move: 'b8c6', probability: 0.249 },
        { move: 'g8h6', probability: 0.064 },
      ],
    },
  },
  // Position 2: Italian Game
  {
    nodeJsResult: {
      value: 0.533,
      policy: [
        { move: 'd2d3', probability: 0.354 },
        { move: 'b1c3', probability: 0.268 },
        { move: 'f3g5', probability: 0.217 },
      ],
    },
  },
  // Position 3: Sicilian Defense
  {
    nodeJsResult: {
      value: 0.519,
      policy: [
        { move: 'g1f3', probability: 0.155 },
        { move: 'f1c4', probability: 0.149 },
        { move: 'b1c3', probability: 0.123 },
      ],
    },
  },
]

// Node.js baselines for Expected Winrate algorithm
// Generated by: npm run test:ew
const EXPECTED_EW_BY_POSITION = [
  // Position 0: Starting Position
  {
    nodeJsResult: {
      bestMove: 'g1f3',
      bestMoveSan: 'Nf3',
      expectedWinrate: 0.587,
      stockfishWinrate: 0.530,
      candidateCount: 3,
    },
  },
  // Position 1: After 1.e4
  {
    nodeJsResult: {
      bestMove: 'e7e5',
      bestMoveSan: 'e5',
      expectedWinrate: 0.555,
      stockfishWinrate: 0.431,
      candidateCount: 3,
    },
  },
  // Position 2: Italian Game
  {
    nodeJsResult: {
      bestMove: 'f3g5',
      bestMoveSan: 'Ng5',
      expectedWinrate: 0.522,
      stockfishWinrate: 0.466,
      candidateCount: 3,
    },
  },
  // Position 3: Sicilian Defense
  {
    nodeJsResult: {
      bestMove: 'c2c3',
      bestMoveSan: 'c3',
      expectedWinrate: 0.483,
      stockfishWinrate: 0.540,
      candidateCount: 3,
    },
  },
]

// =============================================================================
// TYPES
// =============================================================================

interface EngineStatus {
  loading: boolean
  ready: boolean
  error: string | null
  progress: number
}

interface StockfishResult {
  bestMove: string
  evaluation: number
  winrate: number
  depth: number
}

interface MaiaResult {
  // POLICY HEAD: Move play probabilities (how likely is a human to play each move?)
  policy: Array<{ move: string; probability: number }>
  // VALUE HEAD: Position win probability (how likely is the side to move to win?)
  value: number
}

interface EWResult {
  bestMove: string
  bestMoveSan: string
  expectedWinrate: number
  stockfishWinrate: number
  candidateCount: number
  calculationTimeMs: number
}

interface ComparisonResult {
  matches: boolean
  details: string
}

// =============================================================================
// COMPARISON HELPERS
// =============================================================================

/**
 * Check if a value is within a range (inclusive)
 */
function inRange(value: number, min: number, max: number): boolean {
  return value >= min && value <= max
}

/**
 * Check if two numbers are approximately equal (within tolerance)
 */
function approxEqual(a: number, b: number, tolerance: number = 0.05): boolean {
  return Math.abs(a - b) <= tolerance
}

/**
 * Compare Stockfish browser result with expected Node.js result for a given position
 */
function compareStockfish(result: StockfishResult, positionIndex: number): ComparisonResult {
  const expected = EXPECTED_STOCKFISH_BY_POSITION[positionIndex]
  if (!expected) {
    return { matches: false, details: 'No baseline available for this position' }
  }

  const issues: string[] = []
  const nodeJs = expected.nodeJsResult

  // Check if best move is in expected list
  const moveOk = expected.bestMoves.includes(result.bestMove)
  if (!moveOk) {
    issues.push(`Best move "${result.bestMove}" not in expected: [${expected.bestMoves.join(', ')}]`)
  }

  // Check if evaluation is in expected range
  const evalOk = inRange(result.evaluation, expected.evaluationRange.min, expected.evaluationRange.max)
  if (!evalOk) {
    issues.push(`Eval ${result.evaluation}cp outside range [${expected.evaluationRange.min}, ${expected.evaluationRange.max}]`)
  }

  // Check if winrate is close to Node.js result
  const winrateClose = approxEqual(result.winrate, nodeJs.winrate, 0.05)
  if (!winrateClose) {
    issues.push(`Winrate ${(result.winrate * 100).toFixed(1)}% differs from Node.js ${(nodeJs.winrate * 100).toFixed(1)}%`)
  }

  return {
    matches: issues.length === 0,
    details: issues.length === 0 ? 'All values match Node.js baseline' : issues.join('; '),
  }
}

/**
 * Compare Maia browser result with expected Node.js result for a given position
 */
function compareMaia(result: MaiaResult, positionIndex: number): ComparisonResult {
  const expected = EXPECTED_MAIA_BY_POSITION[positionIndex]
  if (!expected) {
    return { matches: false, details: 'No baseline available for this position' }
  }

  const issues: string[] = []
  const nodeJs = expected.nodeJsResult

  // Check if value (win probability) is close
  const valueClose = approxEqual(result.value, nodeJs.value, 0.02)
  if (!valueClose) {
    issues.push(`Value ${(result.value * 100).toFixed(1)}% differs from Node.js ${(nodeJs.value * 100).toFixed(1)}%`)
  }

  // Check if top policy move matches
  if (result.policy.length > 0 && nodeJs.policy.length > 0) {
    const browserTop = result.policy[0].move
    const nodeJsTop = nodeJs.policy[0].move
    if (browserTop !== nodeJsTop) {
      issues.push(`Top policy move "${browserTop}" differs from Node.js "${nodeJsTop}"`)
    }

    // Check if top move probability is close
    const browserProb = result.policy[0].probability
    const nodeJsProb = nodeJs.policy[0].probability
    if (!approxEqual(browserProb, nodeJsProb, 0.02)) {
      issues.push(`Top policy prob ${(browserProb * 100).toFixed(1)}% differs from Node.js ${(nodeJsProb * 100).toFixed(1)}%`)
    }
  }

  return {
    matches: issues.length === 0,
    details: issues.length === 0 ? 'All values match Node.js baseline' : issues.join('; '),
  }
}

/**
 * Compare EW browser result with expected Node.js result for a given position
 */
function compareEW(result: EWResult, positionIndex: number): ComparisonResult {
  const expected = EXPECTED_EW_BY_POSITION[positionIndex]
  if (!expected) {
    return { matches: false, details: 'No baseline available for this position' }
  }

  const issues: string[] = []
  const nodeJs = expected.nodeJsResult

  // Check if best move matches
  if (result.bestMove !== nodeJs.bestMove) {
    issues.push(`Best move "${result.bestMoveSan}" differs from Node.js "${nodeJs.bestMoveSan}"`)
  }

  // Check if expected winrate is close (use larger tolerance since EW is more variable)
  const ewClose = approxEqual(result.expectedWinrate, nodeJs.expectedWinrate, 0.05)
  if (!ewClose) {
    issues.push(`EW ${(result.expectedWinrate * 100).toFixed(1)}% differs from Node.js ${(nodeJs.expectedWinrate * 100).toFixed(1)}%`)
  }

  // Check if stockfish winrate in EW is close
  const sfClose = approxEqual(result.stockfishWinrate, nodeJs.stockfishWinrate, 0.05)
  if (!sfClose) {
    issues.push(`SF winrate ${(result.stockfishWinrate * 100).toFixed(1)}% differs from Node.js ${(nodeJs.stockfishWinrate * 100).toFixed(1)}%`)
  }

  return {
    matches: issues.length === 0,
    details: issues.length === 0 ? 'All values match Node.js baseline' : issues.join('; '),
  }
}

// =============================================================================
// COMPONENT
// =============================================================================

export default function VerifyEnginesPage() {
  // Position selection state
  const [selectedPositionIndex, setSelectedPositionIndex] = useState(DEFAULT_POSITION_INDEX)
  const selectedPosition = TEST_POSITIONS[selectedPositionIndex]

  // Stockfish state
  const [sfStatus, setSfStatus] = useState<EngineStatus>({
    loading: false,
    ready: false,
    error: null,
    progress: 0,
  })
  const [sfResult, setSfResult] = useState<StockfishResult | null>(null)

  // Maia state
  const [maiaStatus, setMaiaStatus] = useState<EngineStatus>({
    loading: false,
    ready: false,
    error: null,
    progress: 0,
  })
  const [maiaResult, setMaiaResult] = useState<MaiaResult | null>(null)

  // Expected Winrate state
  const [ewStatus, setEwStatus] = useState<EngineStatus>({
    loading: false,
    ready: false,
    error: null,
    progress: 0,
  })
  const [ewResult, setEwResult] = useState<EWResult | null>(null)

  // Test Stockfish
  const testStockfish = async () => {
    setSfStatus({ loading: true, ready: false, error: null, progress: 0 })
    setSfResult(null)

    try {
      const { RealStockfish } = await import('@/core/engine/stockfish')
      setSfStatus((s) => ({ ...s, progress: 10 }))

      const stockfish = new RealStockfish()
      setSfStatus((s) => ({ ...s, progress: 30 }))

      await stockfish.init()
      setSfStatus((s) => ({ ...s, progress: 70, ready: true }))

      // Use depth 10 to match Node.js test
      const result = await stockfish.evaluate(selectedPosition.fen, { depth: 10 })

      setSfStatus((s) => ({ ...s, loading: false, progress: 100 }))
      setSfResult({
        bestMove: result.bestMove,
        evaluation: result.cp,
        winrate: result.winrate,
        depth: result.depth,
      })

      stockfish.destroy()
    } catch (error) {
      setSfStatus({
        loading: false,
        ready: false,
        error: error instanceof Error ? error.message : String(error),
        progress: 0,
      })
    }
  }

  // Test Maia
  const testMaia = async () => {
    setMaiaStatus({ loading: true, ready: false, error: null, progress: 0 })
    setMaiaResult(null)

    try {
      const { RealMaia } = await import('@/core/engine/maia')

      const maia = new RealMaia('/maia2/maia_rapid.onnx', (progress) => {
        setMaiaStatus((s) => ({ ...s, progress: Math.min(progress, 90) }))
      })

      setMaiaStatus((s) => ({ ...s, progress: 10 }))
      await maia.init()
      setMaiaStatus((s) => ({ ...s, progress: 95, ready: true }))

      // Use ELO 1500 to match Node.js test
      const result = await maia.predict(selectedPosition.fen, { eloLevel: 1500 })

      setMaiaStatus((s) => ({ ...s, loading: false, progress: 100 }))

      const policyMoves = Object.entries(result.policy)
        .sort(([, a], [, b]) => b - a)
        .slice(0, 5)
        .map(([move, prob]) => ({ move, probability: prob }))

      setMaiaResult({
        policy: policyMoves,
        value: result.value,
      })

      maia.destroy()
    } catch (error) {
      setMaiaStatus({
        loading: false,
        ready: false,
        error: error instanceof Error ? error.message : String(error),
        progress: 0,
      })
    }
  }

  // Test Expected Winrate
  const testExpectedWinrate = async () => {
    setEwStatus({ loading: true, ready: false, error: null, progress: 0 })
    setEwResult(null)

    try {
      const { RealStockfish } = await import('@/core/engine/stockfish')
      const { RealMaia } = await import('@/core/engine/maia')
      const { calculateExpectedWinrate } = await import('@/core/analysis/expectedWinrate')

      setEwStatus((s) => ({ ...s, progress: 10 }))

      const stockfish = new RealStockfish()
      await stockfish.init()
      setEwStatus((s) => ({ ...s, progress: 40 }))

      const maia = new RealMaia('/maia2/maia_rapid.onnx')
      await maia.init()
      setEwStatus((s) => ({ ...s, progress: 70, ready: true }))

      const result = await calculateExpectedWinrate(
        selectedPosition.fen,
        {
          maxCandidates: 3,
          stockfishDepth: 10,
          probabilityThreshold: 0.10,
        },
        stockfish,
        maia
      )

      setEwStatus((s) => ({ ...s, loading: false, progress: 100 }))

      const best = result.candidates[0]
      setEwResult({
        bestMove: best.move,
        bestMoveSan: best.san,
        expectedWinrate: best.expectedWinrateSF,
        stockfishWinrate: best.stockfishWinrate,
        candidateCount: result.candidates.length,
        calculationTimeMs: result.calculationTimeMs,
      })

      stockfish.destroy()
      maia.destroy()
    } catch (error) {
      setEwStatus({
        loading: false,
        ready: false,
        error: error instanceof Error ? error.message : String(error),
        progress: 0,
      })
    }
  }

  // Calculate comparison results (all positions have Node.js baselines now)
  const sfComparison = sfResult ? compareStockfish(sfResult, selectedPositionIndex) : null
  const maiaComparison = maiaResult ? compareMaia(maiaResult, selectedPositionIndex) : null
  const ewComparison = ewResult ? compareEW(ewResult, selectedPositionIndex) : null
  const expectedSf = EXPECTED_STOCKFISH_BY_POSITION[selectedPositionIndex]
  const expectedMaia = EXPECTED_MAIA_BY_POSITION[selectedPositionIndex]
  const expectedEw = EXPECTED_EW_BY_POSITION[selectedPositionIndex]

  return (
    <div style={{ padding: '20px', fontFamily: 'monospace', maxWidth: '900px', margin: '0 auto' }}>
      <h1>🔧 Engine Verification</h1>

      <p style={{ color: '#666', marginBottom: '20px' }}>
        Tests browser engines and compares results against Node.js baseline.
        <br />
        <small>Run <code>npm run test:engines</code> to see Node.js results.</small>
      </p>

      {/* Position Selector */}
      <div style={{ marginBottom: '20px', padding: '15px', background: '#f5f5f5', borderRadius: '8px' }}>
        <strong>Select Test Position:</strong>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '10px' }}>
          {TEST_POSITIONS.map((pos, index) => (
            <button
              key={index}
              onClick={() => {
                setSelectedPositionIndex(index)
                // Clear previous results when position changes
                setSfResult(null)
                setMaiaResult(null)
                setEwResult(null)
              }}
              style={{
                padding: '8px 16px',
                fontSize: '14px',
                cursor: 'pointer',
                background: selectedPositionIndex === index ? '#1976d2' : '#fff',
                color: selectedPositionIndex === index ? '#fff' : '#333',
                border: selectedPositionIndex === index ? '2px solid #1976d2' : '1px solid #ccc',
                borderRadius: '4px',
                fontWeight: selectedPositionIndex === index ? 'bold' : 'normal',
              }}
            >
              {pos.name}
            </button>
          ))}
        </div>
        <div style={{ marginTop: '12px', padding: '10px', background: '#fff', borderRadius: '4px', border: '1px solid #ddd' }}>
          <div style={{ fontWeight: 'bold', marginBottom: '4px' }}>{selectedPosition.name}</div>
          <div style={{ fontSize: '12px', color: '#666', marginBottom: '8px' }}>{selectedPosition.description}</div>
          <code style={{ fontSize: '11px', wordBreak: 'break-all' }}>{selectedPosition.fen}</code>
        </div>
      </div>

      {/* ======== STOCKFISH SECTION ======== */}
      <div
        style={{
          border: '1px solid #ccc',
          borderRadius: '8px',
          padding: '20px',
          marginBottom: '20px',
        }}
      >
        <h2>♟️ Stockfish 17 (WASM vs Node.js)</h2>

        <button
          onClick={testStockfish}
          disabled={sfStatus.loading}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            cursor: sfStatus.loading ? 'not-allowed' : 'pointer',
            background: sfStatus.loading ? '#ccc' : '#4CAF50',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
          }}
        >
          {sfStatus.loading ? 'Loading...' : 'Test Stockfish'}
        </button>

        {sfStatus.loading && (
          <div style={{ marginTop: '10px' }}>
            <div style={{ width: '100%', height: '20px', background: '#eee', borderRadius: '10px', overflow: 'hidden' }}>
              <div style={{ width: `${sfStatus.progress}%`, height: '100%', background: '#4CAF50', transition: 'width 0.3s' }} />
            </div>
            <small>Progress: {sfStatus.progress}%</small>
          </div>
        )}

        {sfStatus.error && (
          <div data-testid="stockfish-error" style={{ marginTop: '10px', padding: '10px', background: '#ffebee', color: '#c62828', borderRadius: '4px' }}>
            <strong>Error:</strong> {sfStatus.error}
          </div>
        )}

        {sfResult && (
          <div style={{ marginTop: '15px' }}>
            {/* Comparison Badge */}
            <div
              style={{
                padding: '8px 12px',
                background: sfComparison?.matches ? '#c8e6c9' : '#fff3e0',
                borderRadius: '4px',
                marginBottom: '10px',
                border: `1px solid ${sfComparison?.matches ? '#4caf50' : '#ff9800'}`,
              }}
            >
              {sfComparison?.matches ? '✅ Browser matches Node.js baseline' : '⚠️ ' + sfComparison?.details}
            </div>

            {/* Results Table */}
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#f5f5f5' }}>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Metric</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Browser (WASM)</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Node.js (Baseline)</th>
                  <th style={{ padding: '8px', textAlign: 'center', borderBottom: '2px solid #ddd' }}>Match</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Best Move</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="sf-best-move">{sfResult.bestMove}</td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>{expectedSf.nodeJsResult.bestMove}</td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {expectedSf.bestMoves.includes(sfResult.bestMove) ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Evaluation</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="sf-evaluation">
                    {sfResult.evaluation > 0 ? '+' : ''}{sfResult.evaluation} cp
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {expectedSf.nodeJsResult.evaluation > 0 ? '+' : ''}{expectedSf.nodeJsResult.evaluation} cp
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {inRange(sfResult.evaluation, expectedSf.evaluationRange.min, expectedSf.evaluationRange.max) ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Win Rate</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="sf-winrate">
                    {(sfResult.winrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {(expectedSf.nodeJsResult.winrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {approxEqual(sfResult.winrate, expectedSf.nodeJsResult.winrate, 0.05) ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px' }}><strong>Depth</strong></td>
                  <td style={{ padding: '8px' }} data-testid="sf-depth">{sfResult.depth}</td>
                  <td style={{ padding: '8px' }}>{expectedSf.nodeJsResult.depth}</td>
                  <td style={{ padding: '8px', textAlign: 'center' }}>
                    {sfResult.depth >= expectedSf.nodeJsResult.depth ? '✅' : '⚠️'}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ======== MAIA SECTION ======== */}
      <div
        style={{
          border: '1px solid #ccc',
          borderRadius: '8px',
          padding: '20px',
          marginBottom: '20px',
        }}
      >
        <h2>🧠 Maia (ONNX Web vs Node.js)</h2>

        <p style={{ color: '#666', fontSize: '14px' }}>
          Note: First load downloads ~89MB model (cached after)
        </p>

        <button
          onClick={testMaia}
          disabled={maiaStatus.loading}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            cursor: maiaStatus.loading ? 'not-allowed' : 'pointer',
            background: maiaStatus.loading ? '#ccc' : '#2196F3',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
          }}
        >
          {maiaStatus.loading ? 'Loading...' : 'Test Maia'}
        </button>

        {maiaStatus.loading && (
          <div style={{ marginTop: '10px' }}>
            <div style={{ width: '100%', height: '20px', background: '#eee', borderRadius: '10px', overflow: 'hidden' }}>
              <div style={{ width: `${maiaStatus.progress}%`, height: '100%', background: '#2196F3', transition: 'width 0.3s' }} />
            </div>
            <small>Progress: {maiaStatus.progress}%</small>
          </div>
        )}

        {maiaStatus.error && (
          <div data-testid="maia-error" style={{ marginTop: '10px', padding: '10px', background: '#ffebee', color: '#c62828', borderRadius: '4px' }}>
            <strong>Error:</strong> {maiaStatus.error}
          </div>
        )}

        {maiaResult && (
          <div style={{ marginTop: '15px' }}>
            {/* Comparison Badge */}
            <div
              style={{
                padding: '8px 12px',
                background: maiaComparison?.matches ? '#c8e6c9' : '#fff3e0',
                borderRadius: '4px',
                marginBottom: '10px',
                border: `1px solid ${maiaComparison?.matches ? '#4caf50' : '#ff9800'}`,
              }}
            >
              {maiaComparison?.matches ? '✅ Browser matches Node.js baseline' : '⚠️ ' + maiaComparison?.details}
            </div>

            {/* VALUE HEAD: Position Win Probability */}
            <div style={{ marginBottom: '15px' }}>
              <strong>🎯 Value Head (Position Win Probability):</strong>
              <p style={{ fontSize: '12px', color: '#666', margin: '4px 0 8px 0' }}>
                How likely is the side to move to win from this position?
              </p>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <tbody>
                  <tr>
                    <td style={{ padding: '8px', background: '#e3f2fd', width: '50%' }}>
                      <strong>Browser:</strong> {(maiaResult.value * 100).toFixed(1)}%
                    </td>
                    <td style={{ padding: '8px', background: '#e8f5e9', width: '50%' }}>
                      <strong>Node.js:</strong> {(expectedMaia.nodeJsResult.value * 100).toFixed(1)}%
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* POLICY HEAD: Move Play Probabilities */}
            <strong>🎲 Policy Head (Move Play Probabilities at ELO 1500):</strong>
            <p style={{ fontSize: '12px', color: '#666', margin: '4px 0 8px 0' }}>
              How likely is a human at this rating to play each move?
            </p>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#f5f5f5' }}>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>#</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Move</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Play %</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Node.js Move</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Node.js %</th>
                  <th style={{ padding: '8px', textAlign: 'center', borderBottom: '2px solid #ddd' }}>Match</th>
                </tr>
              </thead>
              <tbody data-testid="maia-moves">
                {maiaResult.policy.slice(0, 5).map((m: { move: string; probability: number }, i: number) => {
                  const nodeJsMove = expectedMaia.nodeJsResult.policy[i] || null
                  const moveMatches = nodeJsMove && m.move === nodeJsMove.move
                  const probMatches = nodeJsMove && approxEqual(m.probability, nodeJsMove.probability, 0.02)
                  return (
                    <tr key={i} data-testid={`maia-move-${i}`}>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>{i + 1}</td>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid={`maia-move-${i}-uci`}>
                        {m.move}
                      </td>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid={`maia-move-${i}-prob`}>
                        {(m.probability * 100).toFixed(1)}%
                      </td>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                        {nodeJsMove?.move || '-'}
                      </td>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                        {nodeJsMove ? `${(nodeJsMove.probability * 100).toFixed(1)}%` : '-'}
                      </td>
                      <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                        {nodeJsMove ? (moveMatches && probMatches ? '✅' : moveMatches ? '⚠️' : '❌') : '-'}
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ======== EXPECTED WINRATE SECTION ======== */}
      <div
        style={{
          border: '1px solid #ccc',
          borderRadius: '8px',
          padding: '20px',
          marginBottom: '20px',
        }}
      >
        <h2>📊 Expected Winrate (Full Algorithm)</h2>

        <p style={{ color: '#666', fontSize: '14px' }}>
          Tests the complete EW algorithm with real Stockfish + Maia
        </p>

        <button
          onClick={testExpectedWinrate}
          disabled={ewStatus.loading}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            cursor: ewStatus.loading ? 'not-allowed' : 'pointer',
            background: ewStatus.loading ? '#ccc' : '#9C27B0',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
          }}
        >
          {ewStatus.loading ? 'Calculating...' : 'Test Expected Winrate'}
        </button>

        {ewStatus.loading && (
          <div style={{ marginTop: '10px' }}>
            <div style={{ width: '100%', height: '20px', background: '#eee', borderRadius: '10px', overflow: 'hidden' }}>
              <div style={{ width: `${ewStatus.progress}%`, height: '100%', background: '#9C27B0', transition: 'width 0.3s' }} />
            </div>
            <small>Progress: {ewStatus.progress}%</small>
          </div>
        )}

        {ewStatus.error && (
          <div data-testid="ew-error" style={{ marginTop: '10px', padding: '10px', background: '#ffebee', color: '#c62828', borderRadius: '4px' }}>
            <strong>Error:</strong> {ewStatus.error}
          </div>
        )}

        {ewResult && (
          <div style={{ marginTop: '15px' }}>
            {/* Comparison Badge */}
            <div
              style={{
                padding: '8px 12px',
                background: ewComparison?.matches ? '#c8e6c9' : '#fff3e0',
                borderRadius: '4px',
                marginBottom: '10px',
                border: `1px solid ${ewComparison?.matches ? '#4caf50' : '#ff9800'}`,
              }}
            >
              {ewComparison?.matches ? '✅ Browser matches Node.js baseline' : '⚠️ ' + ewComparison?.details}
            </div>

            {/* Results Table */}
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ background: '#f5f5f5' }}>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Metric</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Browser</th>
                  <th style={{ padding: '8px', textAlign: 'left', borderBottom: '2px solid #ddd' }}>Node.js (Baseline)</th>
                  <th style={{ padding: '8px', textAlign: 'center', borderBottom: '2px solid #ddd' }}>Match</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Best Move</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="ew-best-move">
                    {ewResult.bestMoveSan} ({ewResult.bestMove})
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {expectedEw.nodeJsResult.bestMoveSan} ({expectedEw.nodeJsResult.bestMove})
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {ewResult.bestMove === expectedEw.nodeJsResult.bestMove ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Expected Winrate</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="ew-expected-winrate">
                    {(ewResult.expectedWinrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {(expectedEw.nodeJsResult.expectedWinrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {approxEqual(ewResult.expectedWinrate, expectedEw.nodeJsResult.expectedWinrate, 0.05) ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Stockfish Winrate</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="ew-sf-winrate">
                    {(ewResult.stockfishWinrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {(expectedEw.nodeJsResult.stockfishWinrate * 100).toFixed(1)}%
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {approxEqual(ewResult.stockfishWinrate, expectedEw.nodeJsResult.stockfishWinrate, 0.05) ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}><strong>Candidates</strong></td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }} data-testid="ew-candidate-count">
                    {ewResult.candidateCount}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee' }}>
                    {expectedEw.nodeJsResult.candidateCount}
                  </td>
                  <td style={{ padding: '8px', borderBottom: '1px solid #eee', textAlign: 'center' }}>
                    {ewResult.candidateCount === expectedEw.nodeJsResult.candidateCount ? '✅' : '⚠️'}
                  </td>
                </tr>
                <tr>
                  <td style={{ padding: '8px' }}><strong>Calculation Time</strong></td>
                  <td style={{ padding: '8px' }} data-testid="ew-calc-time">{ewResult.calculationTimeMs}ms</td>
                  <td style={{ padding: '8px', color: '#666' }}>-</td>
                  <td style={{ padding: '8px', textAlign: 'center', color: '#666' }}>-</td>
                </tr>
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ======== INFO SECTION ======== */}
      <div style={{ background: '#e8f5e9', padding: '15px', borderRadius: '8px', fontSize: '14px', marginBottom: '20px' }}>
        <h3 style={{ margin: '0 0 10px 0' }}>🖥️ Node.js Testing</h3>
        <p style={{ margin: '0 0 10px 0' }}>
          To run engines in Node.js (without browser):
        </p>
        <pre style={{ background: '#fff', padding: '10px', borderRadius: '4px', overflow: 'auto' }}>
{`npm run test:engines          # Test both engines
npm run test:engines:verbose  # Show detailed output
npm run test:ew               # Test EW algorithm
npm run test:ew:verbose       # Show EW details`}
        </pre>
      </div>

      <div style={{ background: '#fff3e0', padding: '15px', borderRadius: '8px', fontSize: '14px' }}>
        <h3 style={{ margin: '0 0 10px 0' }}>⚠️ Requirements</h3>
        <ul style={{ margin: 0, paddingLeft: '20px' }}>
          <li>Stockfish requires <code>SharedArrayBuffer</code> (needs CORS headers)</li>
          <li>If Stockfish fails, check browser console for CORS errors</li>
          <li>Maia model is ~89MB, first load may take time</li>
          <li>Both engines run entirely in-browser (no server)</li>
          <li>Node.js testing requires: <code>brew install stockfish</code> (macOS)</li>
        </ul>
      </div>
    </div>
  )
}
